# Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes




##Objective
###To predict Reviews for women clothes using Multi Nomial Naive Bayes
Multinomial Naïve Bayes algorithm is a probabilistic learning method that is mostly used in Natural Language Processing. It is also suitable for text classification with discrete feature

## Data Source
[YBI Foundation - Women Clothing.csv ](https://https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv)

##Import Library



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [3]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [5]:
df.shape

(23486, 10)

##Data Pre-Processing
###Removing Missing Values


In [6]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [7]:
df[df['Review']==""]=np.NaN


In [8]:
df['Review'].fillna("No Review",inplace=True)

In [9]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [10]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

##Define Target Variable (y) and Feature Variables (X)

In [11]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [12]:
x = df['Review']



In [13]:
y = df['Rating']

In [14]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

##Train Test Split

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=2529)

In [17]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape


((16440,), (7046,), (16440,), (7046,))

## Feature Text To token conversion

In [18]:
from sklearn.feature_extraction.text import CountVectorizer


In [19]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)

In [20]:
x_train = cv.fit_transform(x_train)

In [21]:
cv.get_feature_names_out()

array(['00 big', '00 petite', '00 regular', ..., 'zipper stuck',
       'zippered pockets', 'zippers buttons'], dtype=object)

In [22]:
x_train.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
x_test = cv.fit_transform(x_test)

In [24]:
cv.get_feature_names_out()

array(['00 32c cup', '00 arm', '00 arm length', ..., 'zone roomy looking',
       'zone style', 'zone style daughter'], dtype=object)

In [25]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Model Training

In [26]:
from sklearn.naive_bayes import MultinomialNB


In [27]:
model = MultinomialNB()

In [28]:
model.fit(x_train,y_train)

MultinomialNB()

##Model Prediction

In [29]:
y_pred = model.predict(x_test)
y_pred

array([1, 2, 2, ..., 1, 1, 3])

In [30]:
y_pred.shape

(7046,)

In [31]:
y_pred

array([1, 2, 2, ..., 1, 1, 3])

## Get Probablity of each Predicted class

In [32]:
model.predict_proba(x_test)

array([[6.98847927e-01, 1.01175491e-01, 1.97917709e-01, 2.47614730e-04,
        1.81125772e-03],
       [3.99697135e-01, 5.06291603e-01, 9.02441096e-02, 2.92305293e-03,
        8.44099357e-04],
       [2.88435579e-01, 5.35610789e-01, 1.26881457e-01, 3.55480909e-03,
        4.55173662e-02],
       ...,
       [5.37872642e-01, 2.16923680e-03, 4.55297477e-01, 5.95809524e-04,
        4.06483450e-03],
       [7.06325521e-01, 1.68233791e-01, 1.20653960e-01, 2.01862081e-03,
        2.76810745e-03],
       [1.61204406e-01, 1.22121106e-01, 3.70131824e-01, 1.48810122e-01,
        1.97732541e-01]])

## Model Evaluation

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

In [34]:
print(confusion_matrix(y_test,y_pred))

[[  71   48   39   47   58]
 [ 139   92   62   74   76]
 [ 282  152  139  118  133]
 [ 555  266  200  204  284]
 [1346  775  600  488  798]]


In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.03      0.27      0.05       263
           2       0.07      0.21      0.10       443
           3       0.13      0.17      0.15       824
           4       0.22      0.14      0.17      1509
           5       0.59      0.20      0.30      4007

    accuracy                           0.19      7046
   macro avg       0.21      0.20      0.15      7046
weighted avg       0.40      0.19      0.23      7046



##Recategories Ratings as Poor(0) and Good(1)

In [36]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Rateing 1,2,3 as 0 and 4,5 as 1

In [37]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [38]:
y = df['Rating']

train test split

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=2529)

In [41]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

Feature text to token

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2, 3), stop_words='english', max_features=50000)

In [44]:
x_train = cv.fit_transform(x_train)

In [45]:
x_test = cv.fit_transform(x_test)

Re - Train Model

In [46]:
from sklearn.naive_bayes import MultinomialNB

In [47]:
model = MultinomialNB()

In [48]:
model.fit(x_train,y_train)

MultinomialNB()

Model Prediction

In [49]:
y_pred = model.predict(x_test)
y_pred.shape

(7046,)

In [50]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

Model Evaluation

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
print(confusion_matrix(y_test,y_pred))

[[ 778  752]
 [2663 2853]]


In [53]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.23      0.51      0.31      1530
           1       0.79      0.52      0.63      5516

    accuracy                           0.52      7046
   macro avg       0.51      0.51      0.47      7046
weighted avg       0.67      0.52      0.56      7046

